language: php

php: 7.3

if: branch = master AND type = push

script:
    # disable xdebug to speed up
    - phpenv config-rm xdebug.ini
    - composer update
    - vendor/bin/monorepo-builder split

notifications:
    email: false
