os: linux

language: php

install:
    - composer update

before_install:
    # disable xdebug if not coverage
    - phpenv config-rm xdebug.ini

jobs:
    include:
        -
            stage: deploy
            name: 'Split Monorepo'
            if: branch = master AND type = push
            php: 7.3
            script:
                - vendor/bin/monorepo-builder split

notifications:
    email: false
