name: Basic Checks

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    basic_checks:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress

            -   run: composer validate-monorepo

            -   run: packages/easy-ci/bin/easy-ci check-conflicts .
