name: Binary Files

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    binary_files:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: |
                    # test run bin files
                    packages/vendor-patches/bin/vendor-patches
