name: Binary Files

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    binary_files:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress

            -   run: packages/vendor-patches/bin/vendor-patches
            -   run: packages/latte-to-twig/bin/latte-to-twig
            -   run: packages/neon-to-yaml/bin/neon-to-yaml
            -   run: packages/class-presence/bin/class-presence
            -   run: packages/easy-ci/bin/easy-ci
